<?php

/**
 * @file
 * Contains ga4_counter.module.
 */

/**
 * Implements hook_cron().
 */
function ga4_counter_cron() {
  // Invalidate the create and update list based on a cache tag.
  $stateKey = 'updated_ga4_counter_cron';
  $lastCleared = \Drupal::state()->get($stateKey);
  $today = date('Y-m-d');
  if ($lastCleared != $today) {
    \Drupal::state()->set($stateKey, $today);
    \Drupal::service('ga_counter.update_service')->updatePathCount();
    \Drupal::service('ga_counter.update_service')->updatePageViews();
    \Drupal::logger('ga4_counter')->notice('ga4_counter gets new data and updates database');
  }
}
